### ISSUE TITLE
All fuel stations appear to be in Sheernes

### ISSUE THREAD

**Issue by Ed-M72** [pantherale0/ha-fuelprices#2]
## System Information

version | core-2023.12.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.58-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4810
Installed Version | 1.33.0
Stage | running
Available Repositories | 1428
Downloaded Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 January 2018 at 00:00
relayer_connected | false
relayer_region | null
remote_enabled | true
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | null
certificate_status | null
instance_id | 638891f9feea4f36861542b1876d4d4d
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 458.4 GB
disk_used | 9.1 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.7.0), Terminal & SSH (9.8.1), Silicon Labs Multiprotocol (2.3.2), Samba share (12.2.0), FTP (4.7.3), Mosquitto broker (6.4.0), Node-RED (16.0.2), MariaDB (2.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 5
views | 25
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 December 2023 at 21:51
-- | --
current_recorder_run | 27 December 2023 at 22:14
estimated_db_size | 267.56 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/pantherale0/ha-fuelprices/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

It doesn't matter what latitude or longitude I use I always get a fuel station in Sheernes. Rather than in 5 miles of my co-ordinates.

### Reproduction steps

1. Create a new location
2. Select a source of tesco, Shell or Morissons
3.
...

### Debug logs

```text
I couldn't work this out.
```

### Diagnostics dump

And this too.

**Comment by pantherale0** [comment]
Hi,

Please attach debug logs, there is a guide in the Home Assistant documentation on enabling debug logging.

https://www.home-assistant.io/docs/configuration/troubleshooting/

Thanks

**Comment by Ed-M72** [comment]
[home-assistant.log](https://github.com/pantherale0/ha-fuelprices/files/13785416/home-assistant.log)

This is the log with debugging turned on.
Ed

**Comment by pantherale0** [comment]
Thanks, will review and update soon.

**Comment by pantherale0** [comment]
I've done a search with the same coordinates as you have used and have returned the following:

```
items:
  - name: Morrisons ME11 5JS
    last_update: "2023-12-28T11:32:14.886548"
    address: Neats Court
    latitude: "51.409688"
    longitude: "0.75805"
    brand: Morrisons
    E10: 138.9
    B7: 146.9
    E5: 148.9
  - name: TESCO ME12 1RH
    last_update: "2023-12-28T11:32:14.886548"
    address: Bridge Road Sheerness
    latitude: 51.442621
    longitude: 0.759551
    brand: TESCO
    E5: 146.9
    E10: 138.9
    B7: 146.9
  - name: SHELL ME12 3EW
    last_update: "2023-12-28T11:32:14.886548"
    address: 265-269 QUEENBOROUGH ROAD
    latitude: 51.414641
    longitude: 0.75856
    brand: SHELL
    B7: 149.9
    E10: 143.9
```

Are you missing fuel stations? If so its because the retailer is not taking part in the temporary open fuel price scheme setup by the CMA (https://www.gov.uk/guidance/access-fuel-price-data)

Its important to note, even if the garage is Esso for example, the retailer that operates this garage might not be Esso themselves, but an independent or another chain.

As far as I can see, the integration is working as expected. I'm looking at other fuel price sources such as https://play.google.com/store/apps/details?id=apposing.petrolprices&hl=en_GB&gl=US&pli=1 to fill the gaps for the missing retailers.
