### ISSUE TITLE
Perfomance issues when running this integration

### ISSUE THREAD

**Issue by trevorwarwick** [pantherale0/ha-fuelprices#44]
## System Information

version | core-2025.2.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.1
os_name | Linux
os_version | 6.6.62-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.5
Stage | running
Available Repositories | 1544
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.2
-- | --
update_channel | stable
supervisor_version | supervisor-2025.02.1
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 220.0 GB
disk_used | 7.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (20.0.0), ESPHome Device Builder (2024.12.4), Studio Code Server (5.18.2), SQLite Web (4.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 0
views | 15
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), end0 (enabled, default, auto), hassio (disabled), docker0 (disabled), veth1167c94 (disabled), veth57e7a41 (disabled), veth625bde3 (disabled), vethaefe30e (disabled), vetha49aa37 (disabled), veth153ba9d (disabled), veth276488a (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), end0 (192.168.0.6/24), hassio (172.30.32.1/23), docker0 (172.30.232.1/23), veth1167c94 (), veth57e7a41 (), veth625bde3 (), vethaefe30e (), vetha49aa37 (), veth153ba9d (), veth276488a ()
ipv6_addresses | lo (::1/128), end0 (2a02:8012:c4c0:1:3718:26c0:d20d:736/64, fe80::1937:e251:ab1a:fc89/64), hassio (fe80::42:40ff:fe0b:190e/64), docker0 (fe80::42:36ff:fe7b:1b00/64), veth1167c94 (fe80::3cda:bbff:fe52:b62b/64), veth57e7a41 (fe80::2cb1:3dff:fe1b:2d3f/64), veth625bde3 (fe80::1019:adff:fef5:8ff7/64), vethaefe30e (fe80::9043:92ff:fe5e:3246/64), vetha49aa37 (fe80::f8fe:d0ff:fe1e:b6b6/64), veth153ba9d (fe80::9499:74ff:fe85:1af9/64), veth276488a (fe80::4407:d0ff:fe33:efe6/64)
announce_addresses | 192.168.0.6, 2a02:8012:c4c0:1:3718:26c0:d20d:736, fe80::1937:e251:ab1a:fc89

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8 February 2025 at 19:27
-- | --
current_recorder_run | 17 February 2025 at 13:16
estimated_db_size | 105.34 MiB
database_engine | sqlite
database_version | 3.47.1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/pantherale0/ha-fuelprices/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I very much like the functionality of this integration, it's very useful. However, I have noticed that my HA system is somewhat less stable when I've got it running.  In particular, whenever fuelprices is enabled, a couple of other integrations start losing connections with their managed devices on a regular basis.

The worst offender is the linkplay integration, because from looking at the code it only allows one missed poll before declaring a device unavailable. Arguably this is also a problem with linkplay, and I've submitted a pull request to improve it, but I've also noticed the issue to a lesser extent with other integrations I'm using.

The effect seems to be worse if the "cheapest N (=5)" feature is enabled in fuelprices, but it still happens occasionally with that disabled.  If I disable fuelprices altogether, there's no problem.

The actual effect on linkplay is as follows:  linkplay makes a REST API call every 10 seconds to get device status.  Looking at a packet capture from tcpdump, this usually completes in a few 10s of milliseconds.  When the poll fails, tcpdump shows that the HA system is very slow in doing the individual bits of the HTTPS request - for example there are gaps of 2-3 seconds between getting a TCP ACK and then sending the next chunk of the request.  It's the sort of effect you'd expect if there was a blocking call somewhere, or a very slow bit of computation, or perhaps a massive deluge of async calls that is swamping the event loop.

fuelprices doesn't seem to contain any debug logging so turning that on didn't help.

I've seen the issue happen as often as 2-3 times a minute, other times it can go for an hour without failing.   

I realise that this is probably a bit vague as a report, but would be interested to know if there's anything else I can do to narrow it down.   My HA system is generally pretty lightly loaded, so I don't think it should be running out of resources in this way.

### Reproduction steps

Use fuelprices in conjuction with the linkplay integration.

### Debug logs

```text
Example section of log where a linkplay request gets no response. In reality what's happening is that HTTP request is processed very very slowly and it actually gets timed out before completing.

2025-02-19 12:50:40.467 DEBUG (MainThread) [linkplay] Request getPlayerStatusEx at https://192.168.0.150
2025-02-19 12:50:40.767 DEBUG (MainThread) [linkplay] Response getPlayerStatusEx: {'type': '0', 'ch': '0', 'mode': '-1', 'loop': '0', 'eq': '0', 'status': 'stop', 'curpos': '0', 'offset_pts': '0', 'totlen': '0', 'Title': '556E6B6E6F776E', 'Artist': '556E6B6E6F776E', 'Album': '556E6B6E6F776E', 'alarmflag': '0', 'plicount': '0', 'plicurr': '0', 'vol': '50', 'mute': '0'}
2025-02-19 12:50:50.470 DEBUG (MainThread) [linkplay] Request getPlayerStatusEx at https://192.168.0.150
2025-02-19 12:51:00.471 DEBUG (MainThread) [linkplay] Request getPlayerStatusEx at https://192.168.0.150
2025-02-19 12:51:00.798 DEBUG (MainThread) [linkplay] Response getPlayerStatusEx: {'type': '0', 'ch': '0', 'mode': '-1', 'loop': '0', 'eq': '0', 'status': 'stop', 'curpos': '0', 'offset_pts': '0', 'totlen': '0', 'Title': '556E6B6E6F776E', 'Artist': '556E6B6E6F776E', 'Album': '556E6B6E6F776E', 'alarmflag': '0', 'plicount': '0', 'plicurr': '0', 'vol': '50', 'mute': '0'}
```

### Diagnostics dump

n/a

**Comment by trevorwarwick** [comment]
Thanks for the reply.

I've currently got all the default UK ones enabled (apart from Jet which broke recently), and there are 34 stations within the radius I defined.

It's quite common to run HA on fairly low powered devices.  If you're already aware of places where your code could be blocking the rest of the system for a long time, or generating a lot of work in one go, maybe there's a way to break up the tasks so other things can make progress ?

I could see from the  debug log  that there's apparently a scheduled update that happens very 30 minutes via the coordinator, but it seems to be doing other stuff between those updates too ?

**Comment by pantherale0** [comment]
The scheduled update via the coordinator actually only tells the modules own update coordinator to perform an update on data sources if they need to.. Intervals are sometimes overridden to something fairly hardcoded to prevent overloading, rate limits and IP bans. Validation of this is implemented in the datasource classes themselves (https://github.com/pantherale0/pyfuelprices/blob/4ede52bdb0513134eabb06dd7d762e14dbf0d07c/pyfuelprices/sources/__init__.py#L100)

The default CMA sources are fairly costly because you can't just query an API, and return a small set of stations, you get all or nothing.

Semaphores are supposed to be implemented to lower the computational cost... but looks like I did it incorrectly so that probably isn't helping to be honest (https://github.com/pantherale0/pyfuelprices/blob/4ede52bdb0513134eabb06dd7d762e14dbf0d07c/pyfuelprices/__init__.py#L30)

Really though, disable the cheapest station sensors if you have them enabled... I don't like the implementation, and a better option would be to use templates instead.. This integration was never supposed to be a "it does everything out of the box" but a number of feature comments and feature requests lead to a pretty hacky implementation that I'm not fond of.

**Comment by trevorwarwick** [comment]
Yes, that use of semaphores doesn't look quite right. If you're trying to spread work over time, I think you'd need to create a single semaphore at a higher level and then acquire/wait for each chunk of computation in that update_src routine ,perhaps ?   As it is, I'm not sure it's doing anything useful.

Anyway, up to you what you want to do with this issue now. It's certainly better with the cheapest N turned off.

**Comment by pantherale0** [comment]
Semaphores has been fixed in latest module version, just need to update the integration.

I would keep cheapest N turned off, and use templates instead.. Here is an example, type is currently set to diesel, location is set for your home location and finally updates every 12 hours or when HA starts. In fact I'm going to deprecate those cheapest sensors because the implementation isn't great, they aren't overly flexible, and with templates you can achieve more.

```
- trigger: 
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: /12
  action:
    - service: fuel_prices.find_fuels
      data:
        location:
          latitude: |
            {{ state_attr('zone.home', 'latitude') }}
          longitude: |
            {{ state_attr('zone.home', 'longitude') }}
          radius: |
            {{ 5 * 1609.34 }}
        type: B7
      response_variable: data
  sensor:
    - name: Home Nearest Fuel Station
      unique_id: Home Nearest Fuel Station
      state: |
        {{ data['fuels'][0].available_fuels.B7 | float }}
      availability: |
        {{ data['fuels'] | count > 0 }}
      state_class: total
      device_class: monetary
      unit_of_measurement: GBP
      attributes:
          other_stations: |
            {{ data['fuels'] }}
          latitude: |
            {{ data['fuels'][0].latitude }}
          longitude: |
            {{ data['fuels'][0].longitude }}
          name: |
            {{ data['fuels'][0].name }}
          station: |
            {{ data['fuels'][0] }}
```

Much more flexibility this way, if you want more stations you could change it like so:

```
- trigger: 
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: /12
  action:
    - service: fuel_prices.find_fuels
      data:
        location:
          latitude: |
            {{ state_attr('zone.home', 'latitude') }}
          longitude: |
            {{ state_attr('zone.home', 'longitude') }}
          radius: |
            {{ 5 * 1609.34 }}
        type: B7
      response_variable: data
  sensor:
    - name: Home Nearest Fuel Station 1
      unique_id: Home Nearest Fuel Station 1
      state: |
        {{ data['fuels'][0].available_fuels.B7 | float }}
      availability: |
        {{ data['fuels'] | count > 0 }}
      state_class: total
      device_class: monetary
      unit_of_measurement: GBP
      attributes:
          latitude: |
            {{ data['fuels'][0].latitude }}
          longitude: |
            {{ data['fuels'][0].longitude }}
          name: |
            {{ data['fuels'][0].name }}
          station: |
            {{ data['fuels'][0] }}
    - name: Home Nearest Fuel Station 2
      unique_id: Home Nearest Fuel Station 2
      state: |
        {{ data['fuels'][1].available_fuels.B7 | float }}
      availability: |
        {{ data['fuels'] | count > 1 }}
      state_class: total
      device_class: monetary
      unit_of_measurement: GBP
      attributes:
          latitude: |
            {{ data['fuels'][1].latitude }}
          longitude: |
            {{ data['fuels'][1].longitude }}
          name: |
            {{ data['fuels'][1].name }}
          station: |
            {{ data['fuels'][1] }}
    - name: Home Nearest Fuel Station 3
      unique_id: Home Nearest Fuel Station 3
      state: |
        {{ data['fuels'][2].available_fuels.B7 | float }}
      availability: |
        {{ data['fuels'] | count > 2 }}
      state_class: total
      device_class: monetary
      unit_of_measurement: GBP
      attributes:
          latitude: |
            {{ data['fuels'][2].latitude }}
          longitude: |
            {{ data['fuels'][2].longitude }}
          name: |
            {{ data['fuels'][2].name }}
          station: |
            {{ data['fuels'][2] }}
```
