### ISSUE TITLE
X lowest prices for specific type of gas around a location

### ISSUE THREAD

**Issue by poudenes** [pantherale0/ha-fuelprices#6]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/pantherale0/ha-fuelprices/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not related to a problem

### Describe the solution you'd like

Create sensors. Imagine you want 5 lowest prices

sensor.lowest_price_1_home
sensor.lowest_price_2_home
sensor.lowest_price_3_home
sensor.lowest_price_4_home
sensor.lowest_price_5_home

sensor.lowest_price_1_work
sensor.lowest_price_2_work
sensor.lowest_price_3_work
sensor.lowest_price_4_work
sensor.lowest_price_5_work

Compare the data and put lowest station in 1, then the next one in 2 etc.

This make it possible to add them in a map

```
  - type: map
    entities:
      - entity: sensor.gas_station_euro95_home_lowest_price_1
        name: LP 1
      - entity: sensor.gas_station_euro95_home_lowest_price_2
        name: LP 2
      - entity: sensor.gas_station_euro95_home_lowest_price_3
        name: LP 3
      - entity: sensor.gas_station_euro95_home_lowest_price_4
        name: LP 4
      - entity: sensor.gas_station_euro95_home_lowest_price_5
        name: LP 5
    geo_location_sources: []
    auto_fit: true
```

### Describe alternatives you've considered

none

### Additional context

none

**Comment by pantherale0** [comment]
Sounds good, perhaps we could look at just creating a single lowest price entity? Then we can use the attributes to store the rest. I think that would provide a cleaner look anyway. What do you think? You would still be able to automate off of state changes to the attributes and create template sensors for something more advanced.

I might move all of the entities over to the sensor platform to be honest anyway, I'm not really using the device_tracker platform how its supposed to be used lol.

**Comment by poudenes** [comment]
That sounds nice as well. One sensor with lowest price as state. And 4 others in attributes. But how will you store all the information that belong to the stations then?

```
source_type: gps
E10: 1.969
B7: 1.769
E5: 2.159
id: directlease_3097
name: Buitenveldert (wz)
address: Parnassusweg 850
postal_code: 1081LC
latitude: 52.33594
longitude: 4.86848
brand: BP
available_fuels:
  E10: 1.969
  B7: 1.769
  E5: 2.159
currency: EUR
last_updated: "2024-01-06T13:40:34.262640"
next_update: "2024-01-07T13:55:35.093557"
friendly_name: Buitenveldert (wz)
```

This will be a very long attribute list if you separate them with a lowest_1_ lowest_2_ before every attribute.
Then 5 different sensors make more sense to keep the information clean for every station.
